<%
    # Convert underscore to camelCase
    under_pat = re.compile(r'_([a-z])')
    def underscore_to_camel(text):
        return under_pat.sub(lambda x: x.group(1).upper(), text)

    def get_singular(name, capitalize = True):
        retval = name
        if (name[len(name)-1] == 's'):
            retval = name[0:len(name)-1]
        if (capitalize):
            retval = retval.capitalize();
        return retval

    def get_plural(name, capitalize = False):
        retval = name
        if (name[len(name)-1] != 's'):
            if (name[len(name)-1] == 'y'):
                name = name[:len(name)-1] + 'ie'
            retval = name + 's'
        if (capitalize):
            retval = retval.capitalize();
        return retval

    # Camel and capitalize
    def name_for_suffix(name, plural=True):
        namex = name
        if (plural):
            namex = get_plural(name);
        return underscore_to_camel(namex).capitalize();

    def service_call(name, method, plural=True):
        return '$this->' + entity_name + 'Service->' + method + name_for_suffix(entity_name, plural);

%><?php
/**
 * Models from schema: ${ model['schema-name'] } version ${ model['version'] }
 * Code generated by ${params['TASK_TYPE_NAME']}
 *
 */


% for entity_name, entity_def in model['entities'].iteritems():
/**
 * Controller class that provides REST API to ${entity_name.capitalize()} resource
 *
 * @todo: Add following line in app/routes.php
 * Route::resource('${entity_name}', '${entity_name.capitalize()}Controller');
 */
class ${entity_name.capitalize()}Controller extends \BaseController {

    // The service object
	protected $${entity_name}Service;

	/**
	 * Constructor
	 */
	public function __construct() {
        $this->${entity_name}Service = new Service\${entity_name.capitalize()}Service();
    }

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
	    $qparams = Input::all();
		$records = ${service_call(entity_name, 'list', False)}($qparams);
		return $list;
	}

	/**
	 * Showing the form is not supported
	 *
	 */
	public function create()
	{
		App::abort(404);
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$data = Input::all();

        try {
            $user = ${service_call(entity_name, 'create', True)}($data);
            return Response::json(array(
                'sid' => $user->sid),
                200
            );
        } catch (Exception $e) {
            return Response::json(array(
                'error' => $e->getMessage()),
                400
            );
        }
	}

	/**
	 * Return JSON representation of the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$record = ${service_call(entity_name, 'find', True)}($id);

		return $record;
	}

	/**
	 * Showing the form is not supported in API.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
	    App::abort(404);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$data = Input::all();

        try {
            $user = ${service_call(entity_name, 'update', True)}($id, $data);
            return Response::json(array(
                'sid' => $user->sid),
                200
            );
        } catch (Exception $e) {
            return Response::json(array(
                'error' => $e->getMessage()),
                400
            );
        }
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		// delete
		$result = ${service_call(entity_name, 'destroy', True)}($id, $data);

		if ($result) {
		    return Response::json(array(
                'error' => false),
                200
            );
		} else {
		    App::abort(404);
		}
	}
}
% endfor
