<%
    def get_sample_val(field):
        type = field['type']
        if (type == 'auto'):
            return 1
        elif (type == 'int'):
            return 1
        elif (type == 'long'):
            return 1
        elif (type == 'datetime'):
            return 'new DateTime'
        endif
        return "'" + field['name'] + "'"

%><?php
/**
 * Models from schema: ${ model['schema-name'] } version ${ model['version'] }
 * Code generated by ${params['TASK_TYPE_NAME']}
 *
 */

% for entity_name, entity_def in model['entities'].iteritems():
/**
 * Copy this file to app/database/seeds directory.
 * Add the line $this->call('${entity_name.capitalize()}TableSeeder');
 * into the DatabaseSeeder.php's run() method.
 * To run the migration script do: $php artisan db:seed
 */
class ${entity_name.capitalize()}TableSeeder extends Seeder {

	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function run()
	{
	    //DB::table('users')->delete();
	    $${entity_name} = [
	        [
% for field in entity_def['fields']:
			'${field["name"]}' => ${get_sample_val(field)},
% endfor
            ]
        ];
        DB::table('users')->insert($users);

	}
}
% endfor
